name: streamlit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - streamlit>=1.30.0
  - pandas>=2.1.0
  - numpy>=1.24.0
  - plotly>=5.18.0
  - pip
  - pip:
    - snowflake-snowpark-python>=1.11.0
